#!/usr/bin/env python3
"""
Generate all schematics for CM5 carrier board.
- Copies CM5, HDMI, USB, IO sheets from CM5 Minima reference (already correct format)
- Generates top-level cm5-carrier.kicad_sch tying all sheets together
- power.kicad_sch already generated by gen_power_schematic.py

Signal mapping (global labels used in power.kicad_sch → hierarchical in other sheets):
  +5V_CM5  → connects to CM5 sheet "+5V" pin
  I2C0_SDA → connects to CM5 sheet "SDA0" pin
  I2C0_SCL → connects to CM5 sheet "SCL0" pin
  VBUS     → connects to USB sheet "5V" pin
"""

import shutil, uuid, re, os

SRC = "/mnt/storage/pcb/cm5-carrier/reference/cm5-minima"
DST = "/mnt/storage/pcb/cm5-carrier"

def uid():
    return str(uuid.uuid4())

# ─── Copy sub-sheets from CM5 Minima (already valid KiCad 8 format) ───────────
for sheet in ["CM5.kicad_sch", "HDMI.kicad_sch", "USB.kicad_sch", "IO.kicad_sch"]:
    src = f"{SRC}/{sheet}"
    dst = f"{DST}/{sheet}"
    shutil.copy2(src, dst)
    # Update title block date
    with open(dst) as f:
        c = f.read()
    c = re.sub(r'\(date "[^"]*"\)', '(date "2026-04-18")', c)
    with open(dst, "w") as f:
        f.write(c)
    print(f"  Copied {sheet}")

# ─── Generate top-level cm5-carrier.kicad_sch ─────────────────────────────────
# Each sheet placed on a grid.  Connections via hierarchical labels.
# Power sheet uses global_label (already written) — no hierarchical pins needed.

def make_sheet(name, filename, x, y, w, h, pins):
    """
    pins: list of (pin_name, pin_type, side, offset_from_top)
    pin_type: input|output|bidirectional
    side: 'left'|'right'
    """
    prop_name = f"""		(property "Sheetname" "{name}"
			(at {x:.2f} {y-1.27:.2f} 0)
			(effects (font (size 1.27 1.27)) (justify left bottom))
		)"""
    prop_file = f"""		(property "Sheetfile" "{filename}"
			(at {x:.2f} {y+h+1.27:.2f} 0)
			(effects (font (size 1.27 1.27)) (justify left top))
		)"""

    pin_strs = []
    for pin_name, pin_type, side, offset in pins:
        px = x if side == "left" else x + w
        py = y + offset
        angle = 180 if side == "left" else 0
        pin_strs.append(f"""		(pin "{pin_name}" {pin_type}
			(at {px:.2f} {py:.2f} {angle})
			(uuid "{uid()}")
		)""")

    pins_str = "\n".join(pin_strs)
    return f"""	(sheet
		(at {x:.2f} {y:.2f})
		(size {w:.2f} {h:.2f})
		(stroke (width 0.152) (type solid))
		(fill (color 255 255 194 0.3020))
		(uuid "{uid()}")
{prop_name}
{prop_file}
{pins_str}
	)"""


def wire(x1, y1, x2, y2):
    return f"""	(wire
		(pts (xy {x1:.2f} {y1:.2f}) (xy {x2:.2f} {y2:.2f}))
		(stroke (width 0) (type default))
		(uuid "{uid()}")
	)"""


def global_label(name, x, y, angle=0, shape="output"):
    return f"""	(global_label "{name}"
		(shape {shape})
		(at {x:.2f} {y:.2f} {angle})
		(fields_autoplaced yes)
		(effects (font (size 1.27 1.27)) (justify left))
		(uuid "{uid()}")
		(property "Intersheet References" ""
			(at 0 0 0)
			(effects (font (size 1.27 1.27)) (hide yes))
		)
	)"""


def net_label(name, x, y, angle=0):
    return f"""	(label "{name}"
		(at {x:.2f} {y:.2f} {angle})
		(fields_autoplaced yes)
		(effects (font (size 1.27 1.27)) (justify left bottom))
		(uuid "{uid()}")
	)"""


def text(s, x, y, size=1.27, bold=False):
    bold_s = "(bold yes)" if bold else ""
    return f"""	(text "{s}"
		(at {x:.2f} {y:.2f} 0)
		(effects (font (size {size:.2f} {size:.2f}) {bold_s}))
		(uuid "{uid()}")
	)"""


elements = []

# ─── Auto-discovered hierarchical labels from each sub-sheet ──────────────────
# CM5:  ['+5V', '1V8_CM4', '3V3_CM4', 'CC1', 'CC2', 'EEPROM_nWP',
#         'ETH_PI{ETH}', 'ETH_nLED_ACTIVITY', 'GLOBAL_EN', 'GPIO4..7',
#         'GPIO_VREF', 'HDMI_PI{HDMI}', 'ID_SC', 'ID_SD', 'PI_nLED_PWR',
#         'PWM', 'PWR_BUT', 'SCL0', 'SDA0', 'TACHO', 'USB2P{USB}',
#         'USBOTG_ID', 'USB_PI{USB}', 'VBUS_EN', 'nLED_ACTIVITY',
#         'nLED_SPEED_100_1000']
# HDMI: ['5V', 'HDMI_C{HDMI}']
# USB:  ['5V', 'USB2C{USB}', 'VBUS_EN']
# IO:   ['3V3', '5V', 'IO5', 'IO6', 'PWM', 'PWR_BUT', 'SCL', 'SDA',
#         'TACHO', 'nACTIVITY_LED', 'nPWR_LED', 'nRESET']

# ─── Layout ───────────────────────────────────────────────────────────────────
#  [POWER  ]   [CM5                ]
#  [       ]   [                   ]
#              [HDMI  ] [USB       ]
#              [IO                 ]

GRID = 2.54  # KiCad standard grid

# Power sheet (top-left) — no hierarchical pins, uses global_label
POWER_X, POWER_Y = 15, 20
power_sheet = make_sheet("Power", "power.kicad_sch",
    POWER_X, POWER_Y, 55, 60,
    []  # no hierarchical pins — power.kicad_sch uses global labels throughout
)
elements.append(power_sheet)

# ─── CM5 sheet (top-right) ────────────────────────────────────────────────────
# Include ALL hierarchical labels from CM5.kicad_sch
CM5_X, CM5_Y = 90, 20
cm5_w, cm5_h = 70, 155

def cm5pin(name, ptype, side, idx):
    """Generate pin tuple at 5.08mm spacing"""
    return (name, ptype, side, (idx+1) * 5.08)

cm5_left = [
    ("+5V",              "input",         "left",  5.08),
    ("+5V",              "input",         "left",  10.16),
    ("+5V",              "input",         "left",  15.24),
    ("3V3_CM4",          "output",        "left",  22.86),
    ("1V8_CM4",          "output",        "left",  27.94),
    ("GPIO_VREF",        "output",        "left",  33.02),
    ("SDA0",             "bidirectional", "left",  40.64),
    ("SCL0",             "bidirectional", "left",  45.72),
    ("CC1",              "bidirectional", "left",  53.34),
    ("CC2",              "bidirectional", "left",  58.42),
    ("PWR_BUT",          "input",         "left",  66.04),
    ("GLOBAL_EN",        "input",         "left",  71.12),
    ("USBOTG_ID",        "input",         "left",  76.20),
    ("ID_SD",            "bidirectional", "left",  83.82),
    ("ID_SC",            "bidirectional", "left",  88.90),
    ("EEPROM_nWP",       "output",        "left",  93.98),
    ("PI_nLED_PWR",      "output",        "left",  101.60),
    ("nLED_ACTIVITY",    "output",        "left",  106.68),
    ("nLED_SPEED_100_1000", "output",     "left",  111.76),
    ("ETH_nLED_ACTIVITY","output",        "left",  116.84),
]
cm5_right = [
    ("HDMI_PI{HDMI}",    "output",        "right", 5.08),
    ("USB2P{USB}",       "output",        "right", 12.70),
    ("USB_PI{USB}",      "output",        "right", 20.32),
    ("VBUS_EN",          "output",        "right", 27.94),
    ("ETH_PI{ETH}",      "output",        "right", 35.56),
    ("GPIO4",            "bidirectional", "right", 43.18),
    ("GPIO5",            "bidirectional", "right", 48.26),
    ("GPIO6",            "bidirectional", "right", 53.34),
    ("GPIO7",            "bidirectional", "right", 58.42),
    ("TACHO",            "input",         "right", 66.04),
    ("PWM",              "output",        "right", 71.12),
]
cm5_sheet = make_sheet("CM5 Connector", "CM5.kicad_sch",
    CM5_X, CM5_Y, cm5_w, cm5_h, cm5_left + cm5_right)
elements.append(cm5_sheet)

# ─── HDMI sheet ───────────────────────────────────────────────────────────────
HDMI_X, HDMI_Y = 185, 20
hdmi_sheet = make_sheet("HDMI Output", "HDMI.kicad_sch",
    HDMI_X, HDMI_Y, 40, 30, [
        ("HDMI_C{HDMI}", "input",  "left", 7.62),
        ("5V",           "input",  "left", 15.24),
    ])
elements.append(hdmi_sheet)

# ─── USB sheet ────────────────────────────────────────────────────────────────
USB_X, USB_Y = 185, 65
usb_sheet = make_sheet("USB Host Ports", "USB.kicad_sch",
    USB_X, USB_Y, 40, 30, [
        ("USB2C{USB}", "input",  "left",  7.62),
        ("5V",         "input",  "left",  15.24),
        ("VBUS_EN",    "input",  "left",  22.86),
    ])
elements.append(usb_sheet)

# ─── IO sheet ─────────────────────────────────────────────────────────────────
IO_X, IO_Y = 90, 190
io_sheet = make_sheet("IO / GPIO / Buttons", "IO.kicad_sch",
    IO_X, IO_Y, 70, 70, [
        ("5V",           "input",         "left",  5.08),
        ("3V3",          "input",         "left",  10.16),
        ("PWR_BUT",      "output",        "left",  17.78),
        ("nRESET",       "output",        "left",  22.86),
        ("SDA",          "bidirectional", "right", 5.08),
        ("SCL",          "bidirectional", "right", 10.16),
        ("TACHO",        "output",        "right", 17.78),
        ("PWM",          "input",         "right", 22.86),
        ("IO5",          "bidirectional", "right", 30.48),
        ("IO6",          "bidirectional", "right", 35.56),
        ("nACTIVITY_LED","input",         "right", 43.18),
        ("nPWR_LED",     "input",         "right", 48.26),
    ])
elements.append(io_sheet)

# ─── Inter-sheet connections ───────────────────────────────────────────────────
# Power → CM5: +5V_CM5 global label connects to CM5 "+5V" hier pins
for oy in [5.08, 10.16, 15.24]:
    elements.append(global_label("+5V_CM5", CM5_X - 20, CM5_Y + oy, angle=180, shape="input"))
    elements.append(wire(CM5_X - 20, CM5_Y + oy, CM5_X, CM5_Y + oy))

# Power → I2C to CM5
elements.append(global_label("I2C0_SDA", CM5_X - 20, CM5_Y + 40.64, angle=180, shape="bidirectional"))
elements.append(wire(CM5_X - 20, CM5_Y + 40.64, CM5_X, CM5_Y + 40.64))
elements.append(global_label("I2C0_SCL", CM5_X - 20, CM5_Y + 45.72, angle=180, shape="bidirectional"))
elements.append(wire(CM5_X - 20, CM5_Y + 45.72, CM5_X, CM5_Y + 45.72))

# CM5 HDMI_PI → HDMI sheet HDMI_C (wire between sheet boxes)
elements.append(wire(CM5_X + cm5_w, CM5_Y + 5.08,   HDMI_X, HDMI_Y + 7.62))
# CM5 +5V (via global) → HDMI 5V
elements.append(global_label("+5V_CM5", HDMI_X + 40 + 10, HDMI_Y + 15.24, angle=0, shape="input"))
elements.append(wire(HDMI_X + 40, HDMI_Y + 15.24, HDMI_X + 40 + 10, HDMI_Y + 15.24))

# CM5 USB2P → USB sheet USB2C
elements.append(wire(CM5_X + cm5_w, CM5_Y + 12.70, USB_X, USB_Y + 7.62))
# CM5 VBUS_EN → USB VBUS_EN
elements.append(wire(CM5_X + cm5_w, CM5_Y + 27.94, USB_X, USB_Y + 22.86))
# USB 5V via global
elements.append(global_label("+5V_CM5", USB_X + 40 + 10, USB_Y + 15.24, angle=0, shape="input"))
elements.append(wire(USB_X + 40, USB_Y + 15.24, USB_X + 40 + 10, USB_Y + 15.24))

# IO sheet power
elements.append(global_label("+5V_CM5", IO_X - 15, IO_Y + 5.08, angle=180, shape="input"))
elements.append(wire(IO_X - 15, IO_Y + 5.08, IO_X, IO_Y + 5.08))
elements.append(global_label("+3.3V_CM5", IO_X - 15, IO_Y + 10.16, angle=180, shape="input"))
elements.append(wire(IO_X - 15, IO_Y + 10.16, IO_X, IO_Y + 10.16))

# IO PWR_BUT → CM5 PWR_BUT (global label bridge)
elements.append(net_label("PWR_BUT_BTN", IO_X + 70 + 5, IO_Y + 17.78))
elements.append(wire(IO_X + 70, IO_Y + 17.78, IO_X + 70 + 5, IO_Y + 17.78))
elements.append(net_label("PWR_BUT_BTN", CM5_X - 5, CM5_Y + 66.04))
elements.append(wire(CM5_X - 5, CM5_Y + 66.04, CM5_X, CM5_Y + 66.04))

# Title / notes
elements.append(text("CM5 Carrier Board — Top Level", 15, 8, size=2.0, bold=True))
elements.append(text("Power via USB-C → BQ25895 charger → LiPo → TPS61089 boost → +5V_CM5", 15, 12))
elements.append(text("Global labels (dotted lines) cross sheet boundaries automatically.", 15, 15))

all_elements = "\n".join(elements)

top = f"""(kicad_sch
\t(version 20231120)
\t(generator "eeschema")
\t(generator_version "8.0")
\t(uuid "{uid()}")
\t(paper "A2")
\t(title_block
\t\t(title "CM5 Carrier Board")
\t\t(date "2026-04-18")
\t\t(rev "1")
\t\t(company "Jens Lennartsson")
\t\t(comment 1 "Raspberry Pi CM5 minimal cyberdeck carrier")
\t\t(comment 2 "USB-C charging, LiPo battery, HDMI, USB-A x2, 40-pin GPIO")
\t)
\t(lib_symbols)
{all_elements}
\t(sheet_instances
\t\t(path "/" (page "1"))
\t)
)
"""

out = f"{DST}/cm5-carrier.kicad_sch"
with open(out, "w") as f:
    f.write(top)
print(f"  Written cm5-carrier.kicad_sch ({len(top):,} bytes)")

print("\nDone. Files written to", DST)
print("  cm5-carrier.kicad_sch  (top-level)")
print("  power.kicad_sch        (already existed)")
print("  CM5.kicad_sch          (copied from reference)")
print("  HDMI.kicad_sch         (copied from reference)")
print("  USB.kicad_sch          (copied from reference)")
print("  IO.kicad_sch           (copied from reference)")
